# Generated by Django 5.2.4 on 2025-08-20 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_eventgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.PositiveIntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='general.booking')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.event')),
            ],
            options={
                'unique_together': {('event', 'ticket_number')},
            },
        ),
    ]
