# Generated by Django 5.2.4 on 2025-08-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
