# Generated by Django 5.2.4 on 2025-08-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_booking_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='custom_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
