# Generated by Django 5.2.3 on 2025-07-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tags',
        ),
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.CharField(choices=[('1 hour', '1 hour'), ('Full night', 'Full night'), ('Full day', 'Full day')], max_length=20),
        ),
    ]
