# Generated by Django 5.2.3 on 2025-07-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_event_tags_alter_event_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.CharField(max_length=20),
        ),
    ]
