# Generated by Django 5.2.4 on 2025-07-24 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
