# Generated by Django 5.2.4 on 2025-08-02 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_delete_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='special_guest',
            new_name='guest',
        ),
    ]
