# Generated by Django 5.2.4 on 2025-08-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_rename_special_guest_event_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='guest_image',
            field=models.ImageField(blank=True, null=True, upload_to='guest_images/'),
        ),
    ]
